const String VERIFY_PAGE = "VERIFY_PAGE";
const String LOG_IN_PAGE = "LOG_IN_PAGE";
const String SIGN_IN_PAGE = "SIGN_IN_PAGE";

const String SYNC_FROM_REMOTE_PAGE = "SYNC_PAGE";
const String CULTIVE_MENU_PAGE = "CULTIVE_MENU_PAGE";
// const String EDIT_TABLE_PAGE = "EDIT_TABLE_PAGE";
const String FORM_DETAIL_TABLE_PAGE = "FORM_DETAIL_TABLE_PAGE";
const String REGISTRY_MAPPING_PAGE = "REGISTRY_MAPPING_PAGE";
const String SEARCH_MAPPING_PAGE = "SEARCH_MAPPING_PAGE";
//MENU CULTIVATION
const String MENU_MAPPING_PAGE = "MENU_MAPPING_PAGE";
const String MENU_GENERAL_PAGE = "MENU_GENERAL_PAGE";
const String MENU_WEEKLY_PAGE = "MENU_WEEKLY_PAGE";
const String MENU_BRANCH_PAGE = "MENU_BRANCH_PAGE";
const String MENU_VEGETAL_GROWTH_PAGE = "MENU_VEGETAL_GROWTH_PAGE";
const String MENU_REPRODUCTIVE_STAGE_PAGE = "MENU_REPRODUCTIVE_STAGE_PAGE";
const String MENU_FRUIT_GROWTH_PAGE = "MENU_FRUIT_GROWTH_PAGE";
// BRANCH COUNT
const String FORM_BRANCH_PAGE = "FORM_BRANCH_PAGE";
const String SEARCH_BRANCH_PAGE = "SEARCH_BRANCH_PAGE";
const String MENU_BRANCH_SAMPLES_PAGE = "MENU_BRANCH_SAMPLES_PAGE";
const String FORM_BRANCH_SAMPLES_PAGE = "FORM_BRANCH_SAMPLES_PAGE";
const String SEARCH_BRANCH_SAMPLES_PAGE = "SEARCH_BRANCH_SAMPLES_PAGE";
// FRUIT GROWTH
const String FROM_FRUIT_GROWTH_PAGE = "FROM_FRUIT_GROWTH_PAGE";
const String SEARCH_FRUIT_GROWTH_PAGE = "SEARCH_FRUIT_GROWTH_PAGE";
// GENERAL COUNT
const String FORM_GENERAL_PAGE = "FORM_GENERAL_PAGE";
const String SEARCH_GENERAL_PAGE = "SEARCH_GENERAL_PAGE";
const String MENU_GENERAL_SAMPLES_PAGE = "MENU_GENERAL_SAMPLES_PAGE";
const String FORM_GENERAL_SAMPLES_PAGE = "FORM_GENERAL_SAMPLES_PAGE";
const String SEARCH_GENERAL_SAMPLES_PAGE = "SEARCH_GENERAL_SAMPLES_PAGE";
//REPRODUCTIVE STAGE
const String FORM_REPRODUCTIVE_STAGE_PAGE = "FORM_REPRODUCTIVE_STAGE_PAGE";
const String SEARCH_REPRODUCTIVE_STAGE_PAGE = "SEARCH_REPRODUCTIVE_STAGE_PAGE";
//VEGETATIVE GROWTH
const String FORM_VEGETATIVE_GROWTH_PAGE = "FORM_VEGETATIVE_GROWTH_PAGE";
const String SEARCH_VEGETATIVE_GROWTH_PAGE = "SEARCH_VEGETATIVE_GROWTH_PAGE";
// WEEKLY COUNT
const String FORM_WEEKLY_PAGE = "FORM_WEEKLY_PAGE";
const String SEARCH_WEEKLY_PAGE = "SEARCH_WEEKLY_PAGE";
const String MENU_WEEKLY_Samples_PAGE = "MENU_WEEKLY_Samples_PAGE";
const String FORM_WEEKLY_SAMPLES_PAGE = "FORM_WEEKLY_SAMPLES_PAGE";
const String SEARCH_WEEKLY_SAMPLES_PAGE = "SEARCH_WEEKLY_SAMPLES_PAGE";
//
const String GRAPHICS_PAGE = "GRAPHICS_PAGE";





const String PALTA_MENU_MAPPING_PAGE = "PALTA_MENU_MAPPING_PAGE";
const String PALTA_REGISTRY_MAPPING_PAGE = "PALTA_REGISTRY_MAPPING_PAGE";
const String PALTA_FORM_DETAIL_TABLE_PAGE = "PALTA_FORM_DETAIL_TABLE_PAGE";
const String PALTA_SEARCH_MAPPING_PAGE = "PALTA_SEARCH_MAPPING_PAGE";