name: flutter_map_booking
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.26+4
  location: ^2.3.5
  http: ^0.12.1
  font_awesome_flutter: ^8.5.0
  flutter_spinkit: ^4.1.1+1
  flutter_rating_bar: ^3.0.0+1
  intro_views_flutter: ^2.8.0
  pin_code_text_field: ^1.5.1
  image_picker: ^0.6.7+12
  geolocator: ^5.3.1 #Use this version packages to get the best performance
  latlong: ^0.6.1
  dio: ^3.0.9
  json_annotation: ^3.0.1
  flutter_swiper: ^1.1.6
  fl_chart: ^0.9.3
  cached_network_image: ^2.1.0+1
  flutter_slidable: ^0.5.4
  material_design_icons_flutter: ^3.2.4595
  flutter_staggered_animations: ^0.1.2
  sliding_up_panel: ^1.0.2
  provider: ^4.0.5
  grouped_buttons: ^1.0.4
  url_launcher: ^5.4.5
  flutter_svg: ^0.17.4
  webview_flutter: ^0.3.20+2
  permission_handler: ^5.0.0

  intl: ^0.16.1
  flutter_calendar_carousel: ^1.4.10
  flutter_tindercard: ^0.1.8
  flutter_html: ^0.11.0
  shimmer: ^1.0.1
  flutter_compass: ^0.3.4
  lite_rolling_switch: ^0.1.1

  firebase_auth: ^0.16.0
  flutter_secure_storage: ^3.3.3
  equatable: ^1.2.0
  device_info: ^0.4.2+9
  firebase_messaging: ^6.0.16
  shared_preferences: ^0.5.8
  image_cropper: ^1.2.3
  mime: ^0.9.7
  firebase_database: ^3.1.6
  firebase_core: ^0.4.4
  pusher_websocket_flutter: ^0.2.0

  flutter_driver:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.2.5
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/icon_taxi/
    - assets/style/
    - assets/image/svg/
    - assets/image/marker/
