name: HTRuta
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.26+4
  http: ^0.12.1
  font_awesome_flutter: ^8.5.0
  flutter_spinkit: ^4.1.1+1
  flutter_rating_bar: ^3.0.0+1
  pin_code_text_field: ^1.5.1
  image_picker: ^0.6.7+12
  geolocator: ^6.0.0 #Use this version packages to get the best performance
  geocoding: ^1.0.2
  latlong: ^0.6.1
  dio: ^3.0.9
  json_annotation: ^3.0.1
  flutter_swiper: ^1.1.6
  fl_chart: ^0.9.3
  cached_network_image: ^2.1.0+1
  flutter_slidable: ^0.5.4
  material_design_icons_flutter: ^3.2.4595
  flutter_staggered_animations: ^0.1.2
  sliding_up_panel: ^1.0.2
  provider: ^4.0.5
  grouped_buttons: ^1.0.4
  url_launcher: ^5.4.5
  flutter_svg: ^0.18.1
  webview_flutter: ^1.0.7
  permission_handler: ^5.0.0

  intl: ^0.16.1
  flutter_calendar_carousel: ^1.4.10
  flutter_tindercard: ^0.1.8
  flutter_html: ^0.11.0
  flutter_switch: ^0.2.2

  flutter_secure_storage: ^3.3.5
  equatable: ^1.2.6
  device_info: ^0.4.2+9
  shared_preferences: ^0.5.12+4
  image_cropper: ^1.2.3
  pusher_websocket_flutter: ^0.2.0

  firebase_auth: ^0.18.4+1
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.0+1
  firebase_database: ^4.4.0
  cloud_firestore: ^0.14.4

  flutter_bloc: ^6.1.3
  get_it: ^5.0.6
  flutter_polyline_points: ^0.2.4
  fluttertoast: ^7.1.8
  flutter_local_notifications: ^4.0.0
  shrink_sidemenu: ^1.0.0+3
  awesome_dialog: ^1.3.2
  video_player: ^1.0.1
  flutter_cache_manager: ^2.1.2
  share: ^0.6.5+4
  vibration: ^1.7.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.2.5
  flutter_launcher_icons: "^0.8.0"
  pedantic: ^1.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icono_app.png"

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/icon_taxi/
    - assets/style/
    - assets/image/svg/
    - assets/image/marker/
    - assets/